version: "3.4"
name: techbanknet

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - techBankNet

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - techBankNet

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "mongodb_data_container:/data/db"
    networks:
      - techBankNet

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: techbankRootPsw
    volumes:
      - "mysql_data_container:/var/lib/mysql"
    networks:
      - techBankNet

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - techBankNet

networks:
  techBankNet:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data_container:
    driver: local
  mysql_data_container:
    driver: local
